### ISSUE TITLE
画像の豆腐化

### ISSUE THREAD

**Issue by KoheiAsano** [HUITCLUB/hokudai_furima#180]
各種画像が豆腐化している
![2018-12-06 15 36 56](https://user-images.githubusercontent.com/32860920/49566086-cb749700-f96c-11e8-9b4b-e1711f0a5db6.png)

**Comment by TetsuFe** [comment]
なんかまた豆腐化してる
正確には画像全部ではなくてicomoonの画像だけ。
S3にはアップされているようではあるが
ファイルにアクセスできないらしい。
また権限を644に変えてみたがダメだった。
どうしたらいいかよくわからない。

**Comment by TetsuFe** [comment]
cloudfrontのキャッシュが残っていると、変更前のファイルがキャッシュヒットしてしまうことがある。
キャッシュヒットは以下の方法で直すことができて、どうやら実際にできるらしいということは確認したが、
https://dev.classmethod.jp/server-side/aws-amazon-cloudfront-deleting-cache-by-invalidation/

しかしそれだけが原因ではないらしい。
権限は結局どうするのが正解なのかよくわからない。
そもそも、もしかすると今まで成功していたのもキャッシュヒットがうまく絡んだ偶然の産物の可能性がでてきた。

**Comment by TetsuFe** [comment]
一応、権限的な話でいうと他のファイルとも同じ権限に戻っているので、そこに関しては問題ないはず。
となると、他との違いはただ一つで、「cssからurl()で画像を取ってきていること」だ。
ここが原因だとしたら、どのようにパス指定するのが良いのだろう？
uurl('fonts/....')としてもダメだった。
だんだんどうすればいいのか分からなくなってくる。

## 気をつけること
- ファイルをアップする前に必ずcloudfrontのキャッシュを削除する
  - 以前のキャッシュを削除して、最新のファイルを反映させるため

**Comment by TetsuFe** [comment]
(index):1 Access to font at 'https://d2h9822qykb13q.cloudfront.net/static/img/fonts/icomoon.woff?aivask' from origin 'https://hufurima.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by TetsuFe** [comment]
これの通りに設定し、img/fonts/*をinvalidationしたら豆腐化が治った！
特にcommitはなし
https://blog.toshimaru.net/s3-cloudfront-cors-setting/
