### ISSUE TITLE
チャットテンプレの提示

### ISSUE THREAD

**Issue by TetsuFe** [HUITCLUB/hokudai_furima#252]
## WHY
- テンプレがないとどんなことをチャットで話せばいいか考える手間がかかる
- 必要なことを伝えられずに面倒なことになる可能性が高まる

## WHAT
- テンプレをチャットページに書いて、円滑にチャットができるようにする

**Comment by Gracer828** [comment]
フォームのSentenceの部分に、テンプレートを載せるという感じでしょうか？

**Comment by Gracer828** [comment]
それとも
・商品の価格交渉や受け渡し方法確認等について、自由にチャットしてください
みたいな説明の部分に書く感じでしょうか？

**Comment by TetsuFe** [comment]
ちょっとIssueのWHATとは別になってしまうけど、別のテンプレ紹介ページを作るのはどうだろう

・商品の価格交渉や受け渡し方法確認等について、自由にチャットしてください
・チャット例はこちら（初めての人は必ずご確認ください）

みたいにリンクを作って、そのリンク先にチャット例のページを作るとかでもいいかも

イメージとしては、第一声で確認すべきことだけ書いておく
以下みたいな感じ


```
チャット例

こんにちは、購入希望ありがとうございます！
販売を確定させていただきました。
以下の点について相談しましょう。

・受け渡し日時
・場所
・連絡手段（Lineなど）

以下のことに注意してチャットするとスムーズにいきます
```

**Comment by TetsuFe** [comment]
とりあえず、sentenceフォームの中には書かない方がいい

sentenceフォームのところにプレースホルダ（灰色のやつ）書いてしまうと、少し書いた時点で消えてしまうから書きづらい

もともとテンプレ文がフォームに入力された状態で始まるようにすると、１回目とかは使いやすいかもだけど２回目以降は削除して自分の文を入れることになって面倒になりそう

**Comment by Gracer828** [comment]
sentenceフォームの中には書かない方がいいという件については了解致しました。

ですが別のテンプレ紹介ページをつくるのは、見るのが面倒になるのと、テンプレを見ながら打つことができなくなるので不便になるような気がします。

**Comment by TetsuFe** [comment]
なるほど
確かにその通りだわ
フォームの下に書いておくのがいいかな

**Comment by TetsuFe** [comment]
まあとりあえずは使えればOKってレベルでいいからあまり凝ったのじゃなくてOK
